### ISSUE TITLE
Bump Stock

### ISSUE THREAD

**Issue by Lukyduk3342** [GTLugo/ExtraGunGear#9]
Is the bump stock still in the mod? im reading through the wiki to check out the mod and i didnt see it, but i saw it in a youtube video. If it has been removed, due to political issues i imagine, is there any chance of another autofire accessory being added? im looking to do an expert gunslinger playthrough with this mod and laserbreak's ak-47, along with a few quality of life mods.

Thanks, and great job! the mod seems fantastic and im excited to play

**Comment by GTLugo** [comment]
I cannot remember everything well from the original mod, but I believe I removed the bump stock because either I couldn't get it to only make guns auto-usable or I couldn't get it to a state I felt was balanced. It definitely wasn't removed due to political reasons hahaha. I will say that I am slowly putting together a rewrite of the mod for 1.4 alpha. Not everything will make it from the original into the rewrite, but I'll keep this in mind when I'm deciding what to keep.
